### PR TITLE
User will no longer have access to UserAdmin

### LINKED ISSUE #621: Restrict access to new admin dashboard for non-admin users (0.3)
### Overview
We have implemented new login functionality to allow users who have projects assigned to them to log in.  However, if they know it's there, they can still access the admin dashboard. We would like to disallow that access. 

### Action Items

The following should happen on login. 
Case 1: Person with accesslevel 'admin' logs in.  They should initially be directed to `/admin`.  

Screen Shot 2021-08-05 at 4 22 46 PM

This person should have full access to everything. 

Case 2: Person with accesslevel 'user' who has managedprojects associated with their id should be able to log in and be directed to `/projects`

Screen Shot 2021-08-05 at 4 29 47 PM

This person should ideally only have access to the `/projects` page. But, since .3 doesn't really have very robust user level authorization, they should at a minimum not have access to `/adminuser'.  

Only someone with user level 'admin' should be able to view this page: 

Screen Shot 2021-08-05 at 4 16 57 PM

The functionality to allow 'user' with managed projects to log in already exists.  Completion of this issue should restrict access of someone with accesslevel 'user'.

### PR DESCRIPTION
**Pull request by WalterT-MK**
Closes #621 

Added Redirect on UserAdmin.js, check auth level is admin or not.

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@WalterT-MK => 

1) This does redirect a user who is not admin, and does not allow access, which is good.  However, it doesn't seem to re-render the the nav bar in the process.  

This is after I was redirected: 
Screen Shot 2021-12-07 at 9 51 32 AM

It's the check-in screen, but it still has the projects nav bar. 

See if you can figure out why it's doing this, and how to fix it.  It seems like it might be related to the issue that Glen was having on his issue, so if you get stuck you might check in with him and see if he has any ideas.  

And we can look at it Thursday.

2) Be sure to start your pull requests with "Closes" and the issue number.  When you do that the issue will automatically be closed when the issue is merged.  I'll add it to this PR.

**Comment by WalterT-MK** [comment]
Yes, I think I know what happened to the nav bar, and I will remember to add the closing at the beginning of PR next time. thanks for reminding me.

**Comment by drubgrubby** [comment]
@WalterT-MK -> I think that Glen's PR ( #695 )that just got merged may have fixed this issue.  You might want to download the development branch and check it out before you do any more work on this.

**Comment by drubgrubby** [comment]
This issue was resolved from the work on issue #695 .  Closing this issue.  On to bigger and better things.

**Pull request closed without merging**
