### PR TITLE
Add project name to dropdown and fix check-in bug

### LINKED ISSUE #1373: Add project name to check-in drop down options
### Overview
The check-in dropdown options are only displaying the name of the meeting, but we need them to also show the name of the project to make it easier for users to select the correct option. Also, we will fix the `undefined` value for the `userId` key of checkIn objects in the database.

### Action Items
- [x] Add project name to the check-in options
- [x] Fix bug that causes `undefined` userId for check-ins

### Resources/Instructions
<details><summary>See screenshot of current drop down options</summary>

image

</details>

<details><summary>See screenshot of undefined userId on checkIn objects</summary>

image

</details>

### PR DESCRIPTION
**Pull request by MattPereira**
Fixes #1373

### What changes did you make and why did you make them ?
  - Removed unnecessary `isLoading` state from `Home.js` that wasn't actually being used
  - Changed the `--SELECT ONE--` option to be more straightforward instead of doing the ol' `await resJson.unshift("--SELECT ONE--");` 
  - Populated the `project` keys of the `EventController.event_list` so that we have access to project names  via the `GET /api/events/` endpoint
  - Fixed `undefined` **userId** being passed to `POST /api/checkins` endpoint in `CheckInForm.js`

### Screenshots of Proposed Changes Of The Website

- Please note that your dropdown options will not be the same since the meeting check-in feature is set up to only allow checkins to meetings when the time of day is near the meeting start time. In order to manually trigger some events to be `checkInReady` [see comment below](https://github.com/hackforla/VRMS/pull/1375#issuecomment-1497843493)

<details>
<summary>Visuals before changes are applied</summary>

image

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

image

</details>

### CODE REVIEW

**Comment by bkmorgan3** [comment]
Hey @MattPereira   In your above screenshots, whats the path youre on? 
OR What are the steps you took to get those screenshots?  I'm not able to get the same views / options in the dropdown.

**Comment by MattPereira** [comment]
@bkmorgan3 the views / options in the dropdown only show `events` that have a `checkInReady: true` 

Easiest way to get some events showing in the dropdown is to just manually edit them in the test db since the mechanism by which they are flipped depends on the actual time of day and a clunky system of cron jobs that run every 30 minutes

- https://github.com/hackforla/VRMS/tree/development/backend/workers

image

**Review by MicahBear — APPROVED** [review]
Hey, @MattPereira, nice job on the meeting name and time display.
Thank you for the additional instructions to see the changes helped a ton.

**Review by plang-psm — APPROVED** [review]

**Pull request merged**
