### PR TITLE
Frontend linter errors

### LINKED ISSUE #293: Fix errors and warnings from compiler
The application has a number of compiler errors as well as runtime errors. At a high level, a great deal of these errors look to be resolved easily with enforcing eslint standards. 

Frontend issues: When you start the react app, a number of warnings and compile errors fill the console. 

Backend issues: When running the application, a number of uncaught async calls breaks the application. 

Overall: Code formatting and linting tools will help us code review faster, and make sure that we are focusing on the feature and not the syntax. Additionally, the tools can help give feedback faster in a programatic way, rather than relying on our own opinions.

### PR DESCRIPTION
**Pull request by nickbeaird**
Overview: Add linter standards for JS files for the longer term, and remove the already present linter errors as seen with the react application. 

Background: The create-react-app has a default linter setup in it's package, which has been outputting errors in our console for some time. The changes in this branch aim to solve those issues and better align the application for coding standards for the future. 

High Level Objectives:
1. Resolve any linter warnings present in the current state of the frontend application
2. Add in Linter standards for the most common linting standards (eslint with AirBNB standards). 
3. Add in prettier settings. 
4. Add in basic VSCode editor settings to reinforce these settings and make development easier.

### CODE REVIEW

**Comment by nickbeaird** [comment]
Here is a before and after:
linters

**Comment by alex-anakin** [comment]
@nickbeaird Will the solution prevent build and application start if there are any violations of linter standards?

**Comment by nickbeaird** [comment]
@alex-anakin, no at this time this PR does not enforce anything at the moment. In general, this would only solve the most egregious errors as listed on the client. This does add more aggressive linter rules though. The next PR will fix all of the more fine grained issues and then be up for enforcement.

**Review by clockwerkz — APPROVED** [review]
Digging it - glad we are now establishing formatting rules and utilizing the prettier tool to save us the headaches of future potential merge conflicts.

**Pull request closed without merging**
