### PR TITLE
replaced html with mui in index

### LINKED ISSUE #1679: Update HTML components to MUI: ./src/components/admin/reports/index.js
### Overview
Review all components in`./src/components/admin/reports/index.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in:`./src/components/admin/reports/index.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [x] Replace these standard HTML components with applicable MUI components. 
    - [x] Make a PR for this file

### Resources
- https://mui.com/base-ui/all-components/
- If you run into any questions, add a comment to the issue and tag "@trillium"

### PR DESCRIPTION
**Pull request by nora-zajzon**
Fixes [#1679](https://github.com/hackforla/VRMS/issues/1679)

### What changes did you make and why did you make them ?

  - Changed all the HTML components to MUI applicable components
  - Used css files to format instead of inline sx to style like @jbubar requested. Caused some visual changes in font and what not. Let me know if this is an issue 

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

Screenshot 2024-09-17 at 11 04 02 AM

</details>

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2024-09-17 at 10 57 45 AM

</details>

### CODE REVIEW

**Comment by nora-zajzon** [comment]
@JackHaeg I made the requested changes for [this](https://github.com/hackforla/VRMS/pull/1706) pr here not sure if i can close the other or if it still has pending merges

**Comment by JackHaeg** [comment]
@nora-zajzon Thank you for making those changes to this PR! Can you please comment directly on the other PR you are referencing above, tag Trillium, and ask him if you can close it?

**Review by trillium — CHANGES_REQUESTED** [review]
Hey @nora-zajzon ,

I'm taking a look at this PR now, thanks for ding a solid tarnsition of the components to MUI. I know that bringing in other MUI components comes with additional challenges in the CSS becuase MUI has some prepackaged styling, and we can solve that in a few ways.

Ideally our normal button styles are normalized across the app, but I don't think that is true for the stats page.

I took a look at the CSS changes, and if we can at all help it I'd prefer if we don't use `!important` in our codebase. Ideally we'd use a more specific selector like `.parent-class .current-class` or `button.current-class` to ensure that the CSS is applied correctly. That way if another dev comes along later and needs to override something they don't have to combat the absolute speicifcity that `!important` requires.

Can you please go through these classes and
 - [ ] `!important` 
 - [ ] Make each selector more specific to override MUI styles instead

CSS can be finicky, so if you need help with this please reach out.

Thanks!

<details>
<summary>Screenshots</summary>

## Current on `dev` and `prod`
image


## With `!important`
image

## Without `!important`
image

</details>

**Review by jbubar — APPROVED** [review]
Requesting to redo this without !important

**Review by jbubar — CHANGES_REQUESTED** [review]
Requesting to redo this without !important

**Comment by JackHaeg** [comment]
@nora-zajzon & @trillium - FYI, it looks like there are a number of other commits that were added to this PR, which have already been merged (e.g., "Create CODE_OF_CONDUCT.md"). Trillium - Nora has provided some more context in the Slack conversation between the 3 of us. Please let her know what next steps to take and how to undo her last push.

**Comment by nora-zajzon** [comment]
Newest commit to this was re done [here](https://github.com/hackforla/VRMS/pull/1748). I am planning to close this.

**Comment by JackHaeg** [comment]
@nora-zajzon In your last comment above, you mentioned that the "_Newest commit to this was re done https://github.com/hackforla/VRMS/pull/1748_", which links to the same page. I assume the latest commit was done here: https://github.com/hackforla/VRMS/pull/1706
- Is that correct?
- Also, am I right to assume you are still planning to close this PR?

**Comment by JackHaeg** [comment]
Closing PR, as new PR has been created here: https://github.com/hackforla/VRMS/pull/1706

**Pull request closed without merging**
