### PR TITLE
Implement logout

### LINKED ISSUE #695: Logout: can't log out
### Overview
As the a PM, I want users to be logged out of the application on demand and on a time out so that we increase security of the applications data

### Action Items
Determine what holds the login state and model what files are being touched by the logout process and identify what would be needed to logout and propose logout method to team, get approval, execute changes.

### PR DESCRIPTION
**Pull request by glenflorendo**
Resolves #695

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@glenflorendo -> The code all looked so good I was really hopeful when I clicked that 'logout' button.  But sadly I got the following errors:

<details>
<summary>Logged in as 'admin' on the 'Projects' link</summary>

Screenshot 2021-11-30 at 19-45-12 VRMS
</details>

<details>
<summary>Logged in as 'admin' on the 'Admin' tab</summary>


Screenshot 2021-11-30 at 19-47-05 VRMS

</details>

Will I ever be able to log out?  Time will tell...

**Comment by glenflorendo** [comment]
@drubgrubby Thanks for giving me those screenshots! I think I know the issue. I'll continue to work on this. ☺️

**Comment by glenflorendo** [comment]
@drubgrubby I integrated the logout logic with the current auth context. Please let me know if there are any issues. 😄

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@glenflorendo => We are rapidly approaching perfection, but we have not quite arrived. 

The logout functionality works great.  

It seems like the re-rendering is still a little weird. 
<details>
<summary>These are the navigation links when you are logged in</summary>
Screen Shot 2021-12-06 at 1 00 00 PM
</details>

It seems that when you are in the projects module and you click 'logout', it logs you out and returns you to the logged out screen.

However, when you are in either the Admin module (http://localhost:3000/useradmin) or the Events module (http://localhost:3000/events) it seems lo logout just fine, but it doesn't seem to re-render completely.  

<details>
<summary>Admin module - Logged out</summary>

Screen Shot 2021-12-06 at 12 26 01 PM
</details>

<details>
<summary>Events Module - Logged out</summary>

Screen Shot 2021-12-06 at 12 23 02 PM

</details>

**Comment by drubgrubby** [comment]
@glenflorendo  => Perfect!  Thanks so much for your persistence on this. 

Ready to merge.

**Review by drubgrubby — APPROVED** [review]

**Pull request merged**
