### PR TITLE
Bkmorgan3 1336/server respond with new proj

### LINKED ISSUE #1336: Make server respond to project creation POST request with the newly created project id
### Overview
When a project is created via `POST` request to `/api/projects/`, the response does not contain the newly created project's id. We want to respond with that new project id so we can redirect users to the newly created project's details page.

### Action Items
- [ ] Figure out if it is possible to have the backend respond with information about the newly created project
- [ ] Make the necessary changes to the code or let team know it is not feasible

### Resources/Instructions
- The create project routing logic is found in `controllers/project.controller.js` on line 16
- The project model is in `models/project.model.js`
<details><summary>See current response object after creating a new project</summary>

image

</details>

### PR DESCRIPTION
**Pull request by bkmorgan3**
Fixes #1336 

### What changes did you make and why did you make them ?

  - Altered the response in the creation handler of the API to return the ID
  - Set the ID to state
  - redirect once the ID is not null

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by MicahBear** [comment]
Available: 05/05/23

**Review by trillium — APPROVED** [review]
Pulled down and tested this PR. Great job!

Redirect works exactly as expected. 🎊🎊🎊🎊

**Comment by plang-psm** [comment]
Available: 6hrs
Expected: 5/8/23

**Review by plang-psm — APPROVED** [review]
Great work @bkmorgan3!

**Pull request merged**
