### PR TITLE
replaced babel-eslint  with @babel/eslint-parser

### LINKED ISSUE #667: Find a replacement to babel-es-lint
### Overview
Dependabot created a pr for updating one of the dependencies for babel-eslint and it broke everything, 

Turns out babel-eslint is deprecated so we need to find a replacement

### Action Items
- [ ] how is babel es lint being used
- [ ] replace references with whatever

### Resources/Instructions
- [command to search npm dependencies](https://classic.yarnpkg.com/en/docs/cli/why/)
- [babel-eslint npm page](https://www.npmjs.com/package/babel-eslint)
- Braking dependabot pr's
    - #664
    - #663

### PR DESCRIPTION
**Pull request by evanyang1**
fixes #667

### CODE REVIEW

**Review by jasonwong26 — APPROVED** [review]
Nice work @evanyang1!

This looks good to me.  @jbubar, what do you think?

**Review by jbubar — APPROVED** [review]
Looks Great! Nice work Evan. Everything works great on my end

**Comment by jbubar** [comment]
@evanyang1 && @jasonwong26 .. one more thing.. could we do this same thing for the 0.4 backend also?

# Relevant files
https://github.com/hackforla/VRMS/blob/edbbd5641a593c1fff1fb8aa46ec43219712ed38/backend-mvp-04/package.json#L18
https://github.com/hackforla/VRMS/blob/edbbd5641a593c1fff1fb8aa46ec43219712ed38/backend-mvp-04/.eslintrc.json#L2

**Review by jbubar — CHANGES_REQUESTED** [review]
see comment above

**Review by jbubar — APPROVED** [review]
Everything looks good

**Pull request merged**
