### PR TITLE
Fix display issue with TitledBox in Project Form

### LINKED ISSUE #1646: Fix display issue with TitledBox in Project Form
### Overview
The TitledBox children have been accidently moved outside of the component, rendering them differently than before:
Screenshot 2024-05-12 at 17 12 47

### Action Items
 - [ ] Move children back within TitledBox regardless of edit mode

### PR DESCRIPTION
**Pull request by lcchrty**
Fixes #1646

### What changes did you make and why did you make them ?

  - Placed child components within TitleBox component to properly render the component
  - Bug introduced from previous PR

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by trillium — CHANGES_REQUESTED** [review]
In running this I'm getting an error. It looks like isLoading hasn't been defined or passed in as props. Can you take a look?

```js
./src/components/ProjectForm.js
   Line 277:40:  'isLoading' is not defined  no-undef
```

**Comment by JackHaeg** [comment]
@lcchrty just checking in! Would you be able to take a look at the error @Spiteless posted above?

**Comment by lcchrty** [comment]
> In running this I'm getting an error. It looks like isLoading hasn't been defined or passed in as props. Can you take a look?
> 
> ```js
> ./src/components/ProjectForm.js
>    Line 277:40:  'isLoading' is not defined  no-undef
> ```

I'll look into this -- I think some edits from another issue I was working on wormed their way into this PR.

**Review by trillium — CHANGES_REQUESTED** [review]
Sorry for slow-walking this. We ended up with a merge conflict.

Would you like to take a crack at it first? I'm happy to help resolve it if needed :)


```sh
# git fetch upstream
# git merge upstream/development
M  CONTRIBUTING.md
UU client/src/components/ProjectForm.js                   # merge conflict here
M  client/src/components/admin/donutChartContainer.js
M  client/src/components/admin/donutChartLoading.js
M  client/src/components/auth/Auth.js
M  client/src/pages/ManageProjects.js
M  client/src/sass/AdminLogin.scss
```

**Comment by lcchrty** [comment]
Hey @trilliumsmith, I found the problem! I was working on another ticket that got merged before this one, so there are missing pieces of state and some conditional rendering for the updated save button that isn't showing up. Screenshot below.
I'm planning to update this week before our first meeting in August!
Screenshot 2024-07-28 at 09 06 16

**Review by lcchrty — COMMENTED** [review]
draft of requested changes

**Comment by lcchrty** [comment]
@trillium merge conflict resolved! CI/CD failing though...

**Comment by JackHaeg** [comment]
FYI - the failing tests are not an issue with your PR specifically, this has to do with the CI/CD pipeline.

**Review by trillium — APPROVED** [review]
Thanks for this fix :)

**Pull request merged**
