### PR TITLE
Fix/blocks non admins editing project details

### LINKED ISSUE #1143: Remove the ability to edit anything for the people who are not admin
### Overview
We spoke to bonnie, and because we do not have an audit feature, we do not want to let the people in hack for la.

This is only removing the edit field from the project lead admins,

and it needs to have a disclaimer on the page that says  - 'The data here is only test data and is not accurate'

### Action Items
- [x] remove the edit ability on the projects page for the limited admin users
- [x] needs to have a disclaimer on the page that says  - 'The data here is only test data and is not accurate'
- [ ] edit the md file that is linked on our github

### Resources/Instructions

https://github.com/hackforla/VRMS/pull/1146#issuecomment-1161168843

### LINKED ISSUE #1157: Disable limited users’ ability to new create projects thru the ‘add new project’ button in the useradmin component
### Overview
Currently, any user can click on the 'add new project' button in the user admin component and create a new project. This needs to be prevented and grant access only to the allowed type of user.

### Action Items

- [x] Check user permissions for the current user and conditionally render, or redirect user to its allowed areas in the app

NEXT STEPS:

### Resources/Instructions
background: issue #1105

### PR DESCRIPTION
**Pull request by chukalicious**
closes #1143
closes #1157

- adds test data disclaimer
- blocks users from editing project detail fields
- blocks users from creating a new project

### CODE REVIEW

**Comment by chukalicious** [comment]
https://www.loom.com/share/9a6eb96c0cef4e238d8c610f3fd27a20

**Review by jbubar — APPROVED** [review]
This looks great! looked at the code, and pulled it onto my branch and ran the app! Nice work Kat! This is a big step towards moving on from v0.3

**Comment by jbubar** [comment]
Ready to merge

**Review by FoxShaunR — APPROVED** [review]
Looks great!

**Pull request merged**
