### PR TITLE
Migrated v0.3 to /reference/ folder

### LINKED ISSUE #635: v0.4 Setup Infrastructure Epic
# Story
There is no story for this epic.  This contains a number of tasks related to preparing the v0.4 branch for general development.

# Tickets

## Environment
- [x] #645
- [x] #646
- [x] #647
- [x] #648
- [x] #649
- [x] #650
- [x] #651
- [x] #653 

## Database
- [ ] #659
- [x] #660

## Linting
- [x] Copy over linting rules from development branch
- [x] #688

### Backend
- [x] #686
- [x] Address warnings for rule: max-len
- [ ] Address warnings for rule: no-prototype-builtins
- [ ] Address warnings for rule: no-undef
- [ ] Address warnings for rule: no-unused-vars

### Frontend
- [x] #687
- [ ] Address warnings for rule: camelcase
- [ ] Address warnings for rule: import/extensions
- [ ] Address warnings for rule: import/newline-after-import
- [ ] Address warnings for rule: import/no-duplicates
- [ ] Address warnings for rule: import/no-extraneous-dependencies
- [ ] Address warnings for rule: import/no-named-as-default-member
- [ ] Address warnings for rule: import/order
- [ ] Address warnings for rule: import/prefer-default-export
- [ ] Address warnings for rule: jest/expect-expect
- [ ] Address warnings for rule: jest/no-standalone-expect
- [ ] Address warnings for rule: jest/valid-expect
- [ ] Address warnings for rule: jest/valid-title
- [ ] Address warnings for rule: jest-dom/prefer-checked
- [ ] Address warnings for rule: jest-dom/prefer-enabled-disabled
- [ ] Address warnings for rule: jest-dom/prefer-in-document
- [ ] Address warnings for rule: jsx-a11y/click-events-have-key-events
- [ ] Address warnings for rule: jsx-a11y/label-has-associated-control
- [ ] Address warnings for rule: jsx-a11y/no-static-element-interactions
- [ ] Address warnings for rule: max-classes-per-file
- [ ] Address warnings for rule: no-nested-ternary
- [ ] Address warnings for rule: no-param-reassign
- [ ] Address warnings for rule: no-return-await
- [ ] Address warnings for rule: no-shadow
- [ ] Address warnings for rule: no-unused-expressions
- [ ] Address warnings for rule: no-unused-vars
- [ ] Address warnings for rule: no-use-before-define
- [ ] Address warnings for rule: prefer-const
- [ ] Address warnings for rule: prefer-destructuring
- [ ] Address warnings for rule: prefer-promise-reject-errors
- [ ] Address warnings for rule: prettier/prettier
- [ ] Address warnings for rule: react/button-has-type
- [ ] Address warnings for rule: react/no-array-index-key
- [ ] Address warnings for rule: react/no-unescaped-entities
- [ ] Address warnings for rule: react-hooks/exhaustive-deps
- [ ] Address warnings for rule: spaced-comment
- [ ] Address warnings for rule: testing-library/no-node-access

## Miscellaneous
- [ ] Remove references to `cypress` test platform
- [ ] Remove references to `http-proxy-middleware` package
- [ ] Update README with instructions for using local Docker environment
- [x] #666
- [ ] Update Contributing document to instruct folks to merge PRs to v0.4 Branch
- [ ] Update README for v0.4

### LINKED ISSUE #647: Address eslint errors in Backend
# v0.4 Setup Infrastructure

This ticket prepares us to implement the PR Validation actions by ensuring we have a clean environment - with passing test and linting rules.

Note: changes here are temporary.  Once the #582 PR is merged into development we will use those instead.

# Dependencies
- #645

# Instructions
- [ ] Run the `npm run lint` on the backend folder.
- [ ] Address each reported error by either:
  - modifying the code
  - modifying the relevant eslint rule to treat the issue as a warning

# Acceptance Criteria
Running the `npm run lint` command should not return any errors.

### LINKED ISSUE #648: Address eslint errors in Client
# v0.4 Setup Infrastructure

This ticket prepares us to implement the PR Validation actions by ensuring we have a clean environment - with passing test and linting rules.

Note: changes here are temporary.  Once the #582 PR is merged into development we will use those instead.

# Dependencies
- #645

# Instructions
- [ ] Run the `npm run lint` on the client folder.
- [ ] Address each reported error by either:
  - modifying the code
  - modifying the relevant eslint rule to treat the issue as a warning

# Acceptance Criteria
Running the `npm run lint` command should not return any errors.

### LINKED ISSUE #649: Address failing tests in Backend
# v0.4 Setup Infrastructure

This ticket prepares us to implement the PR Validation actions by ensuring we have a clean environment - with passing tests and linting rules.

# Dependencies
- #645

# Instructions
- [ ] Run the `npm run test` command on the backend folder.
- [ ] Address each failing test

# Acceptance Criteria
Running the `npm run test` command should not return any errors.

### PR DESCRIPTION
**Pull request by jasonwong26**
# Summary

Ok, LOTS of changes in this one.  Good luck evaluating file by file!  (Seriously, don't - that would suck).  Recommend pulling down latest and reviewing in a stand alone environment.

Summary of changes:

- Migrated v0.3 to /reference/folder
- Addressed broken tests in `backend` due to inconsistent export syntax in `/services/` folder
- Disabled all EsLint rules in `backend` (this change is temporary - will be replaced with rules created in PR #582
- Disabled all EsLint rules in `client` (this change is temporary - will be replaced with rules created in PR #582
- Removed unused/stale scripts from root, backend, and client `project.json` files
- Re-added `/api/healthcheck` endpoint to `backend`
- Re-added `/healthcheck` endpoint to `client`

# Acceptance Criteria

Please confirm that in your environment:
- running the root `npm run start` script properly starts both backend and client services.
- All tests pass for both backend and client.
- Running the `npm run lint` script passes without error.

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@jasonwong26  - Thanks for all of your help getting this up and running.  

Really amazing work getting this all sorted out!

**Startup**

Ran `npm run start` and got the following: 

<details>
<summary>Failed to Compile error: </summary>
Screen Shot 2021-08-12 at 12 21 42 PM
</details>

Then I got the same error for `HandleAuth`.

I changed the capitalization on lines 5 and 6 of `./src/routes/index.js` to `Auth` and `HandleAuth` and then it seems to have started up just fine. 

<details>
<summary>Edited lines 5 & 6</summary>
Screen Shot 2021-08-12 at 12 34 12 PM
</details>

**Tests**

1 failed test in backend.

<details>
<summary>Client Tests</summary>
Screen Shot 2021-08-12 at 12 39 37 PM
</details>

<details>
<summary>Backend Test</summary>
Screen Shot 2021-08-12 at 12 41 14 PM
</details>

** Lint **
`npm run lint` ran without errors, but also without anything at all.  Not sure if this is correct.  (from within ./client/) 

Edit-> Subsequently ran from ./backend with same response. 

Perhaps I needed to run this in some other manner. ?

<details>
<summary>Lint</summary>
Screen Shot 2021-08-12 at 12 49 07 PM
</details>

**Comment by jasonwong26** [comment]
Thanks for reviewing this @drubgrubby!

I've pushed the file rename changes that were missed by in the last push (git doesn't detect case sensitive changes).  I chose to update the file names rather than the import statements in order to try and be more consistent in file names (other component files are camelCase, so I think it makes sense to keep these that way).

Regarding the empty ES Lint result... yup!  I basically removed all of the rules so we could get to a point where the linting check passes without error.  As we add rules back into the project I'm sure we'll get more warnings, etc.

Please take another look and let me know if you still encounter errors.

NOTE: you may have to force the download of the renamed files (unless you set your environment up to be case sensitive).

**Review by drubgrubby — COMMENTED** [review]
@jasonwong26 => Looks great!  

npm run start worked fine.  

It did compile with a couple of warnings, but I think that's okay.  Please confirm.
Screen Shot 2021-08-13 at 8 05 20 AM

All ./client tests passed. 

Screen Shot 2021-08-13 at 8 13 26 AM


One ./backend test was skipped, all the rest passed. 

Screen Shot 2021-08-13 at 8 08 49 AM

lint ran on both client and backend without any output, as it should. 

Please confirm that the compile warnings are not to be worried about at the moment (or don't confirm that, as is appropriate), and I'll approve and merge.  

<happy face>

**Comment by jasonwong26** [comment]
Hi @drubgrubby!

Thanks for reviewing the changes!  Yes, your results are consistent with mine (see below).  The compilation warnings are carried over from the existing client code (I didn't change much there).  Same with the skipped backend test.

There will be additional cleanup needed after this PR is merged in, but this gets to a point where we can have multiple people work on v0.4.

Thanks!

### Backend
image
image

### Client
image
image

**Review by drubgrubby — APPROVED** [review]
Looks good.  Ready to merge.

**Pull request merged**
