### PR TITLE
feat: Validate Google drive, but not sure how to use custom error msg

### LINKED ISSUE #1369: Form Validation - Google Drive URL
### Overview
Currently, the projects details form doesn't have any validation. It increases onboarding time because user needs to go back and frequently correct typos (Form validation). The Google Drive URL must be a required AND validated field.

### Action Items
The project’s form fields need data validation, as opposed to them being free text fields. The `Google Drive URL` field should:
- [x] Change the `Google Drive URL` field to be a required field (_this field is required to be filled out in order to save edits on an existing project / create a new project_).
  - [x] Add error message to Google Drive URL when this field is left unfilled by a user: "Google Drive URL is required" in red text.
- [x] Add in validation to the `Google Drive URL` field -- https://drive.google.com/[          ] - (_This will be a placeholder that will allow the user to copy and paste the final URL_) 
  - [x] Add a validation Error message: "Invalid URL" in red text. This error message should be displayed when a user enters a URL other than a Google Drive URL. 

### Resources/Instructions
Usability Zoom Recording Timestamp 3:35
https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

### PR DESCRIPTION
**Pull request by evanyang1**
Fixes #1369 
(Sort of)

### What changes did you make and why did you make them ?

  - Add `validate` function to data.js for google drive field
  - Add validate field to register object
  -
!! I didn't find out how to do a custom error message.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Comment by JackHaeg** [comment]
FYI - the requirement to validate Google Drive has changed since this PR was delivered, and this function will likely be dropped. I will confirm with the stakeholder tomorrow and update/close this PR pending approval.

**Comment by trillium** [comment]
@JackHaeg Looking to resolve this, did we get confirmation on this requirement?

**Comment by JackHaeg** [comment]
@trillium & @evanyang1 Per discussion with stakeholder, Google Drive URL is a required field. So, this PR is still relevant and this fix is necessary. 

However, we ask that prior to merging, please update the custom error message to read "Invalid URL". Once this custom error message is in place, please feel free to merge this PR if it meets all other acceptance criteria. Plan to discuss during today's All Team MTG call.

**Comment by JackHaeg** [comment]
@trillium Can you please provide Evan with some assistance on how to create this custom error message ("Invalid URL")?

**Comment by JackHaeg** [comment]
@evanyang1 
- Confirmed with stakeholder that this is a required field and that the error message needs to be updated to "Invalid URL". In short: 
- Existing Requirements = validated as a Google Drive URL
- NEW Requirements: 
  - The Google Drive URL field itself is required to be filled out in order to save edits on an existing project / create a new project (Google Drive URL = REQUIRED field) 
  -  If the Google Drive URL is not validated, error message should read "Invalid URL" 

**Plan for this PR:**
- Before merging, please submit a new PR with the following additional requirements: 
  - [ ] Make Google Drive URL field a required field. (error message when field is left unfilled = "Google Drive URL is required")
  - [ ] Update Validation Error message to "Invalid URL" (i.e., when user enters a URL other than a Google Drive URL)

**Comment by jbubar** [comment]
This is a good start and could potentially be used by the next person who picks up https://github.com/hackforla/VRMS/issues/1369

**Pull request closed without merging**
