### PR TITLE
Create search input as a new UI element

### LINKED ISSUE #488: Create search input as a new UI element
### Overview

Create search input as a new UI element (based on finalized 0.4 Style Guide).

Find mockup here => [Finalized v0.4 Style Guide (Figma), page 2](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)

search-input

### Action Items

- [x] Explore existing implementation for UI elements:
- `src/sass/elements`
- DEV UI KIT web page (run locally) http://localhost:3001/dev-ui-kit, take a look at the element `Input with icon`
- DEV UI KIT component https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js

- [x]  Create JSX for new UI element inside `/*** INPUTS ***/` section in [`src/utils/uiKit`](https://github.com/hackforla/VRMS/blob/development/client-mvp-04/src/utils/uiKit/uiKit.js)
- [x]  Add styles for new UI element inside `src/sass/elements/_inputs.scss`
- [x]  Make sure a new UI element looks and works like in Style Guide

### Resources/Instructions
[Finalized v0.4 Style Guide (Figma)](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=25453%3A28)
Dev UI Kit web page (run locally) http://localhost:3001/dev-ui-kit

### PR DESCRIPTION
**Pull request by piall**
Created search input as a new UI element #488 .
If have any fixes let me know :smiley:

### CODE REVIEW

**Comment by OlgaBilogurova** [comment]
Hi @mdPial, please pull changes from the `development` branch and resolve conflicts.

**Comment by piall** [comment]
Hello @OlgaBilogurova , Was on line 154  `</div>` removed and added after progress bar's `</div>`  by mistake ?
```diff
  <div className={'inputs-container'}>
        <h1 className={'kit-sec-title'}>*** INPUTS ***</h1>
  
        <Input placeholder={'Enter your email'} type={'email'} />
        <p className={'dev-comment'}>Default Input, components/common/input</p>
- </div>
```

**Comment by OlgaBilogurova** [comment]
Hi @mdPial, thank you for pointing on this.
`</div>` should be moved from 153 to 227 line to close `inputs-container` block.

**Review by OlgaBilogurova — APPROVED** [review]
Looks good to me, approved

**Comment by piall** [comment]
It's my pleasure. I was waiting for your reply to push the fix for the conflicts.

**Comment by piall** [comment]
Hi @OlgaBilogurova  fixed merge conflicts. Should I merge approved changes on my own?

**Review by OlgaBilogurova — APPROVED** [review]

**Comment by OlgaBilogurova** [comment]
> Hi @OlgaBilogurova fixed merge conflicts. Should I merge approved changes on my own?

Hi, @mdPial thank you, merged.

**Comment by piall** [comment]
It's my pleasure. Thank you for helping.

**Pull request merged**
