### PR TITLE
fixes: 1234 Place edit icon in Recurring Events

### LINKED ISSUE #1234: As a Admin-level user (Bonnie), I want to know where to click to edit meeting times, so that I can quickly make changes to meeting times
### Overview
When tasked with editing meeting time, it wasn't clear to the user that "Recurring Events block" was clickable. The only way for user to know that it was a clickable item, was to hover over it. However, during testing, our user didn't hover over the block, so they had no idea how to edit the meeting time and needed guidance from VRMS team.

### Action Items
- [ ] Add a [edit icon] next to each meeting time. For example, if project has multiple events, each event should have an edit hyperlink next to it.
- [ ] Size and color should be consistent with existing [edit icon] hyperlinks

### Acceptance Criteria
Gherkin Syntax:
    Scenarios: All the actions a user could take (including bad input)
    GIVEN: Sets the context. What page are we on and what state are we in? Is the user an admin? Signed-in? Has created a campaign?
    WHEN: What actions the user is performing. What event occurred?
    THEN: What should the system do in response? What is the expected outcome?

Scenario: Admin level user is tasked to edit existing project meeting time
GIVEN: That the admin level user is on the Projects page
AND there is an existing meeting time
WHEN they go to edit existing meeting time
THEN there should be a clear [edit icon] next to corresponding meeting time that the user can click to edit meeting time.

### Resources/Instructions

- [Zoom timestamp: 20:54]

- Screen Shot 2022-10-17 at 10 51 01 AM

- Usability Testing recording: https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

### PR DESCRIPTION
**Pull request by bkmorgan3**

### CODE REVIEW

**Comment by bkmorgan3** [comment]
Screen Shot 2023-02-15 at 3 34 52 PM

**Comment by bkmorgan3** [comment]
Is there a final word on how the finished work should look?  I followed the directions in the Action Items section but see mention of an icon to use.  
My thoughts are:
1- The icon will disrupt the consistency of the page 
2- The attached icon might need some trimming work - when I downloaded and opened it, I see a tiny icon on a full page.

But will do whatever the team thinks is best.

**Review by MattPereira — APPROVED** [review]
Nice simple implementation of flexbox with a well named `.event-list-details` class.

Normally I would nitpick about leaving the `// justify-content: space-between` comment in the CSS file, but since we weren't given a figma design for this issue I'm okay with leaving it as a viable alternative alignment option. Up to you if you'd like to remove the comment.

Well done @bkmorgan3 :+1:

**Comment by bkmorgan3** [comment]
@MattPereira   Removed commented code

**Review by jbubar — APPROVED** [review]
Pulled this down and it looks good to me as well. Thanks brad and Matt

**Pull request merged**
