### PR TITLE
Update HTML to MUI in VRMS/client/src/components/admin/reports /index.js

### LINKED ISSUE #1679: Update HTML components to MUI: ./src/components/admin/reports/index.js
### Overview
Review all components in`./src/components/admin/reports/index.js` and replace all standard HTML components with applicable MUI components.

### Action Items
- [x] Review components in:`./src/components/admin/reports/index.js` and search for any standard HTML components.
  - _IF all components are already updated to relevant MUI_
    - [ ] Comment on this issue that all components are already updated to MUI. 
    - [ ] Close the issue & check the box associated with this issue on the [MUI issue epic](https://github.com/hackforla/VRMS/issues/1617)
    - [ ] Move on to the next [MUI issue](https://github.com/hackforla/VRMS/issues/1617) 
  - _IF standard HTML components are found in the file:_ 
    - [x] Replace these standard HTML components with applicable MUI components. 
    - [x] Make a PR for this file

### Resources
- https://mui.com/base-ui/all-components/
- If you run into any questions, add a comment to the issue and tag "@trillium"

### PR DESCRIPTION
**Pull request by nora-zajzon**
Fixes #1679 

### What changes did you make and why did you make them ?

  - Changed all the HTML components to MUI applicable components

<details>
<summary>Visuals after changes are applied</summary>

Screenshot 2024-07-24 at 8 20 02 PM

</details>

### CODE REVIEW

**Comment by trillium** [comment]
Hey @nora-zajzon, I see that you've taken on multiple tickets as we've gone throught he month of July:

- #1626
- #1640
- #1641
- #1680

Thanks for taking these on!

It looks like each subsequent PR you're making is including the changes from work on the previous issue (this PR contains changes to 4 files). At the moment it is fine, but please do take care to revert to the `development` branch for each new PR. It helps us keep changes to the application in smaller chunks so that if there's an issue we can roll back changes in smaller amounts.

Planning on reviewing them in the order that they were submitted :)

**Review by trillium — CHANGES_REQUESTED** [review]
Hey @nora-zajzon, can you double check your commits locally? I don't see any file changes to `client/src/components/admin/reports/index.js` in this PR

**Comment by nora-zajzon** [comment]
@trillium Do you still want me to submit a pr for index even though it is not in the current iteration of the app? I do have it locally so I can

**Comment by trillium** [comment]
No, if you'd prefer to pass on it you're welcome to. If you'd like to see it through we'll review and accept it :)

**Comment by jbubar** [comment]
@nora-zajzon is going to take an action on this. she was unsure if it was important

**Comment by nora-zajzon** [comment]
Closing this PR due to two being open

**Pull request closed without merging**
