### PR TITLE
redirect form /admin to /projects if user is not admin

### LINKED ISSUE #621: Restrict access to new admin dashboard for non-admin users (0.3)
### Overview
We have implemented new login functionality to allow users who have projects assigned to them to log in.  However, if they know it's there, they can still access the admin dashboard. We would like to disallow that access. 

### Action Items

The following should happen on login. 
Case 1: Person with accesslevel 'admin' logs in.  They should initially be directed to `/admin`.  

Screen Shot 2021-08-05 at 4 22 46 PM

This person should have full access to everything. 

Case 2: Person with accesslevel 'user' who has managedprojects associated with their id should be able to log in and be directed to `/projects`

Screen Shot 2021-08-05 at 4 29 47 PM

This person should ideally only have access to the `/projects` page. But, since .3 doesn't really have very robust user level authorization, they should at a minimum not have access to `/adminuser'.  

Only someone with user level 'admin' should be able to view this page: 

Screen Shot 2021-08-05 at 4 16 57 PM

The functionality to allow 'user' with managed projects to log in already exists.  Completion of this issue should restrict access of someone with accesslevel 'user'.

### PR DESCRIPTION
**Pull request by vadzimk**
Closes #621

@drubgrubby Not completely sure that the access to user who is not admin has been restricted bc i could not create a new user myself. 
Please check.

There is a warning that is related to useAuth hook. I commented about it in  #23

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@vadzimk -> My apologies.  I don't think the issue itself was written very clearly.  I have re-written the issue to, hopefully, clarify the desired behavior. 

Your changes do restrict someone with access 'user' so that they can not access the `/admin/ directory, which is good. 

The directory that I'm more concerned with is the `/useradmin` directory.  This is associated with the 'Admin' navigation link, which is what confused me and why I subsequently confused you. 

Someone logged in as 'user' can still access the `/useradmin`/ directory. They should not be able to access that directory. 

Finally, when I'm logged in as a 'user' and I try to go to `/admin` it seems to kick me all the way out to the login screen, and then send me back to `/projects`.  That works, in that access is denied, but it's kind of a funky user experience. 

Nice work, and again, sorry for the lack of clarity on my part.  If you would like additional clarification, let me know and we can go over it. 

When/where are you seeing that useauth() error?  I'm not seeing it, or I'm not looking in the right place.  Perhaps we can look at it at the meeting tonight if you're going to be there.

**Comment by vadzimk** [comment]
Maybe fixing authorization in this app is a bit over my head because it does not fully redirect as you probably expect.
Would be great if someone could show me the right way of solving authorization in protected routes.
I have pushed some changes. Please check.

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@vadzimk -> This is close, but not quite there.  

After this update, it does allow the correct access if you are a 'user' or an 'admin'.  However, on initial login both groups are sent back to the login page. Then when you click the 'login' button again, you go to the proper place. 

I don't have time to dig into this today, but let me look more closely on Sunday as I'm not sure exactly how to solve this either at the moment.  

Thanks for all of your work on this.

**Comment by vadzimk** [comment]
@drubgrubby That redirect to '/login' happens because the user is falsy somewhere outside the components that you wanted to change access to. 
v3 uses context api to manage user state which causes a lot of trouble including that login not working properly. 
v4 is using redux which is right. If i were to touch the auth state i would change it to redux and it'd involve a lot of code changes. So i would not do it because v3 is going to be retired.

**Comment by vadzimk** [comment]
@drubgrubby @jasonwong26 
In order to close it, remember there was a bug that you would need to refresh the page after clicking the magic link for the first time. Since it was fixed, now it will not redirect to login because the user is true. We just need to resolve the conflict below: `authLevelRedirect` should be called with `auth.user?.accessLevel` argument:
 `authLevelRedirect(auth.user?.accessLevel)`
I have no idea how to resolve conflicts yet.

**Comment by drubgrubby** [comment]
PR incomplete. Closing until further notice.

**Pull request closed without merging**
