### PR TITLE
add length validation to description field

### LINKED ISSUE #1363: Form Validation - Description
### Overview
We need to add validation to the project description field that matches the allowable characters in the databases for the field, and throw a message when the validation fails the input, so that users can understand why their input is being rejected.

#### Details
Currently, the projects details form doesn't have any validation. It increases onboarding time because user needs to go back and frequently correct typos (Form validation)

The project’s form fields need data validation, as opposed to them being free text fields.

- Description: criteria - Max 250 characters

### Action Items
- [x] Add validation
- [x] Add Error message: 
   - Description is too long, max 250 characters allowed

### Resources/Instructions
Usability Zoom Recording Timestamp 3:35
https://drive.google.com/drive/u/0/folders/1oSUAaU-fzKHpXeZpou5PH3SwC5eRnEWq

### PR DESCRIPTION
**Pull request by bkmorgan3**
Fixes #1363 

### What changes did you make and why did you make them ?

  - added regex value for all characters, max of 250

### CODE REVIEW

**Comment by MattPereira** [comment]
Since the `ProjectForm` component only controls creating new projects the current state of this PR does not stop existing projects from being updated to have > 250 character descriptions

**Comment by bkmorgan3** [comment]
@MattPereira I see.  I assumed it was lumped in with the other new project validation / react hook form work.  I'll refactor

@Spiteless  Whats the best path forward here?  Its kind of an anti pattern to have to forms written two different ways.  Do we edit the ticket, use one form component, or edit the scope ?

**Comment by trillium** [comment]
We're going toward getting both the Create and Edit pages being derived from one component with validations passed to the root component (#1471 does this now). Happy to get this validation working and then extend it across the project properly.

**Comment by trillium** [comment]
Waiting to merge #1471 first, then this PR will need to be rebased

**Comment by bkmorgan3** [comment]
@Spiteless   updated.

**Comment by trillium** [comment]
Hey @bkmorgan3 , can you redo these changes on the current version of development. The file location has moved to `client/src/components/data.js` and is creating merge conflicts that we can sidestep

**Review by trillium — CHANGES_REQUESTED** [review]
Can you redo these changes on the current version of dev in the new `client/src/components/data.js` file and force push?

**Comment by bkmorgan3** [comment]
@Spiteless This update to dev was done after my pr was submitted.  done.

**Review by trillium — APPROVED** [review]
Silly me, I thought there'd be conflicts here but there are not

**Pull request merged**
