### PR TITLE
Fix: broken link to issue board in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pluto-bell**
### What changes did you make and why did you make them ?

  - Changed link to the issue board's `Prioritized Backlog` because current link was taking me to a 404 page.
 #### Note
- If there's a different link that is preferred, let me know and I'll happily switch it out. 

### Screen Captures of Proposed Changes

<details>
<summary>Screen Capture before changes are applied</summary>

https://github.com/user-attachments/assets/5ab22374-18d6-46fe-86d0-21d385826ad3

</details>

<details>
<summary>Screen Capture after changes are applied</summary>

https://github.com/user-attachments/assets/2a44ba56-8aa3-4f53-99a6-e883fc495beb

</details>

### Links to test yourself
[Current CONTRIBUTING.md — click on the "Prioritized Backlog Column" link](https://github.com/hackforla/VRMS/blob/development/CONTRIBUTING.md#31-claim-an-issue)
[Fixed CONTRIBUTING.md — click on the "Prioritized Backlog Column" link](https://github.com/pluto-bell/VRMS/blob/fix-broken-issues-link/CONTRIBUTING.md#31-claim-an-issue)

### CODE REVIEW

**Comment by vorleakyek** [comment]
@pluto-bell, is there a ticket number that can be linked in the PR comment?

**Comment by pluto-bell** [comment]
@vorleakyek, I didn't make an issue since the onboarding instructions didn't make mention of creating one, only making a PR: 
Screenshot 2024-10-28 at 12 25 29 PM


Reference Issue: #1800

**Comment by vorleakyek** [comment]
@pluto-bell, sounds good. I just want to make sure.

**Review by JackHaeg — APPROVED** [review]
Thanks for these updates, Pluto!

**Pull request merged**
