### PR TITLE
Add welcome landing page with wiki link for admin and project managers

### LINKED ISSUE #1353: Adding new welcome page and allowing admin dashboard access from navbar
### Overview
Our stakeholder has requested that we create a new welcome page for users to land on after clicking the magic link sent to their email. Additionally, we will add the admin dashboard page component to the nav-bar.

### Action Items
- [x] Create a new welcome page component in the `src/pages/` folder called `UserWelcome.js`
- [x] Greet the user with a friendly message and offer them this link to the vrms User Guide wiki `https://github.com/hackforla/VRMS/wiki/User-Guide`
- [x] Add another button to the `Navbar.js` component that links to the `/admin` route ( follow same pattern as other buttons )
- [x] Add a link to the logo so that it navigates users to `/` path if not logged in or `/weclome` if they are authenticated

### Instructions
- When a user clicks the magic link, it should take them directly to the new welcome landing page
- This is the only time the user will have access to the welcome page

### Resources
- https://github.com/hackforla/VRMS/blob/development/client/src/components/Navbar.js

### PR DESCRIPTION
**Pull request by MattPereira**
Fixes #1353

### What changes did you make and why did you make them ?
  - Added a welcome page so that we can provide users with a link to the wiki page explaining how to use the app
  - Added `STATS` option to navbar so that admin users still have convenient access to the dashboard after first landing on the welcome page
  - Added a link to the hfla logo so that anon users are directed to `/` and logged in users are taken to `/welcome`
  - Added a `history.push('/')` to the `logout()` function so that users are redirected to default anon landing page when they logout
  - Moved organization logo to the left side of navbar as requested by stakeholder during live meeting

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  

image

</details>

### CODE REVIEW

**Review by trillium — APPROVED** [review]
Pulled this down and checked it out. Great work @MattPereira !!

As an aside, we need project linting. I had difficulty following the changes because there was a lot of additional clutter from tab/spaces, single/dub quote etc.

**Review by MicahBear — APPROVED** [review]
I pulled down to review on local and @MattPereira Nice work! The visual changes look great.  @Spiteless called it with the project linting.  But still great work.

**Review by trillium — APPROVED** [review]
Good work @MattPereira ! Nice clean update

**Review by MicahBear — APPROVED** [review]
Quick turn around!

**Pull request merged**
