### PR TITLE
Fix frontend warnings, minor tweaks

### LINKED ISSUE #1302: Address all warnings occurring the ./client/src/pages folder
### Overview
We want to systematically expunge all warnings from the code base so that its easier to work on and less stuff breaks in the future. For this issue, we will try to handle all of the warnings thrown by files in the `./client/src/pages` folder

### Action Items
Resolve the following warnings:
- [x] `./src/pages/EmailSent.js`
  Line 13:8:  React Hook useEffect has a missing dependency: 'props.history'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
- [x] `./src/pages/Success.js`
    - [x] Line 15:11:  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji
    - [x] Line 16:11:  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji
    - [x] Line 17:11:  Emojis should be wrapped in <span>, have role="img", and have an accessible description with aria-label or aria-labelledby  jsx-a11y/accessible-emoji
- [x] `./src/pages/UserDashboard.js`
  Line 1:17:  'useEffect' is defined but never used  no-unused-vars
- [x] `./src/pages/UserProfile.js`
  Line 1:17:  'useEffect' is defined but never used  no-unused-vars
- [x] `./src/pages/ReturningUser.js`
    Line 1:27:  'useEffect' is defined but never used  no-unused-vars
- [x] `./src/pages/ProjectLeaderDashboard.js`
    - [x] Line 245:6:  React Hook useEffect has a missing dependency: 'getDashboardInfo'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
    - [x] Line 249:6:  React Hook useEffect has a missing dependency: 'getAttendees'. Either include it or remove the dependency array
    - [x] Line 253:6:  React Hook useEffect has a missing dependency: 'getRoster'. Either include it or remove the dependency array 
    - [x] Line 257:6:  React Hook useEffect has a missing dependency: 'getNextEvent'. Either include it or remove the dependency array
- [x] `./src/pages/Event.js`
    - [x] Line 30:18:  'setCheckInReady' is defined but never used  
    - [x] Line 53:6:   React Hook useEffect has a missing dependency: 'fetchEvent'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
- [x] `./src/pages/Events.js`
    - [x] Line 32:6:   React Hook useEffect has a missing dependency: 'fetchData'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
    - [x] Line 51:19:  'event_city' is assigned a value but never used 
    - [x] Line 52:19:  'event_state' is assigned a value but never used 
- [x] `./src/pages/Home.js`
    - [x] Line 40:8:  React Hook useEffect has a missing dependency: 'fetchEvents'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
- [x]  `./src/pages/CheckInForm.js`
    - [x] Line 447:6:  React Hook useEffect has a missing dependency: 'fetchQuestions'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

### Resources/Instructions
- Communicate with the team about any errors that are unsolvable or you think are not worth solving because of upcoming changes to the app
- Feel free to address minor refactors of the code like using alias imports or `&&` instead of ternary operators

### LINKED ISSUE #1303: Address all warnings occurring in the ./client/src/components folder
### Overview
We want to systematically expunge all warnings from the code base so that its easier to work on and less stuff breaks in the future. For this issue, we will try to handle all of the warnings thrown by files in the `./client/src/components` folder.

### Action Items
- [x] `./src/components/auth/Auth.js`
Line 104:6:  React Hook useEffect has a missing dependency: 'handleLogin'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
- [x] `./src/components/manageProjects/editProject.js`
Line 23:9:  'recrutingDataFormatted' is assigned a value but never used  no-unused-vars
- [x] `./src/components/auth/HandleAuth.js`
    - [x] Line 24:6:   React Hook useEffect has a missing dependency: 'props.location.search'. Either include it or remove the dependency array 
    - [x] Line 32:5:   React Hook useEffect has a missing dependency: 'auth.isError'. Either include it or remove the dependency array   
    - [x] Line 44:7:   React Hook useEffect has a missing dependency: 'auth'. Either include it or remove the dependency array
    - [x] Line 44:26:  React Hook useEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked
- [x] ./src/components/manageProjects/utilities/addDurationToTime.js
Line 33:4:  Expected an error object to be thrown  no-throw-literal
- [x] `./src/components/ReadyEvents.js`
Line 33:8:  React Hook useEffect has a missing dependency: 'fetchEvent'. Either include it or remove the dependency array
- [x] `./src/components/admin/dashboard/index.js`
Line 384:6:  React Hook useEffect has missing dependencies: 'getAndSetData' and 'getNextEvent'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
- [x] `./src/components/dashboard/AttendeeTable.js`
    - [x] Line 42:41:  Expected to return a value in arrow function
    - [x] Line 62:8:   React Hook useEffect has a missing dependency: 'sortAttendees'. Either include it or remove the dependency array
- [x] `./src/components/dashboard/RosterTable.js`
    - [x] Line 54:13:  'email' is assigned to itself
    - [x] Line 55:14:  'fileId' is assigned to itself
    - [x] Line 82:9:   'gitHubClickHandler' is assigned a value but never used
- [x] `./src/components/admin/donutChartContainer.js`
    - [x]  Line 75:6:  React Hook useEffect has missing dependencies: 'createArc', 'createPie', and 'pieData'. Either include them or remove the dependency array

### Resources/Instructions
- Communicate with the team about any errors that are unsolvable or you think are not worth solving because of upcoming changes to the app
- Feel free to address minor refactors of the code like using alias imports or `&&` instead of ternary operators

### PR DESCRIPTION
**Pull request by trillium**
Fixes #1302 
Fixes #1303

### What changes did you make and why did you make them ?

  - Removed (boolen ? component : null) pattern, switched to (boolen && component) pattern
  - rename headerToSend on import, save from defining it multiple places for fetch calls
  - Resolve eslint warnings (each commit has notes on resolved warning)

<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
  
image

</details>

### CODE REVIEW

**Review by MattPereira — APPROVED** [review]
Although my intention was to split fixing the warnings into two separate pull requests

- #1303 
- #1302 

Since all the features of the app still work and nothing seems to be broken, I'm okay shipping this sooner rather than later just to get it done so we can all enjoy this beautiful warning free startup log


<details><summary>See screenshot</summary>

Screenshot from 2023-03-05 15-53-51

</details>



We will have to work on our communication moving forward :rofl: 


One question tho, do you remember what `yarn` command you ran that resulted in the `backend/yarn.lock` and `client/yarn.lock` files being updated?

**Review by plang-psm — APPROVED** [review]
Nice work @Spiteless ! Site runs smooth, no errors upon starting, and code looks clean. I do agree with @MattPereira , essentially we should have 1 pull request per issue, but these changes may be beneficial to push now.

**Comment by trillium** [comment]
Thanks!

> One question tho, do you remember what `yarn` command you ran that resulted in the `backend/yarn.lock` and `client/yarn.lock` files being updated?
> 

Yes , npx update can-I-use

I'm on my phone, that might not be exactly right

Edit:

Info 

https://github.com/browserslist/browserslist/issues/492

**Comment by trillium** [comment]
> communication going forward

Agreed. I didn't realize this was going to be two issues and had done the majority of the work already prior to the issue being generated. Will be more communicative in the future.

**Pull request merged**
