### PR TITLE
update all packages to a new major version while tests pass

### LINKED ISSUE #651: Address outdated NPM packages and audit warnings in Backend
# v0.4 Setup Infrastructure

This ticket addresses NPM warnings related to versions and security.

# Dependencies
- #645

# Instructions
- [x] Run the `npm outdated` script.  Document all of the warnings that are returned.
- [x] Address each warning:
  - for minor package updates - go ahead and update to the latest version
  - form major package updates - research the package version change to identify (as best you can) the breaking changes.  Raise the version change as a topic for discussion in a team meeting.
- [x] Run the `npm audit` or `yarn outdated` script.  Document all of the warnings that are returned.  Hopefully most issues will be resolved via addressing the outdated packages, but for those that remain Raise these as a topic for discussion in a team meeting.
- [ ] Apply all major package updates that the team feels are worth pursuing.  Address any build errors that occur due to the changes.

# Acceptance Criteria
Running the `npm outdated` and `yarn audit` commands should pass without error (unless the group decides that it is out of scope to address an issue for a given package).

### PR DESCRIPTION
**Pull request by vadzimk**
Closes #651
I ran ncu --doctor -u 
It ensures that tests pass with the new version rules.

### CODE REVIEW

**Comment by jasonwong26** [comment]
Hi @vadzimk!

Nice use of the `npm-check-updates` package!  You've definitely resolved the majority of the outdated packages.  I do see that the number of audit warnings is still high - can you tell me which package is the source of most of the warnings?  I also see that some of the packages weren't updated to the latest available minor versions.  Any idea why?

__Something to thing about when using the `npm-check-updates` package:__
It is only as good as the unit tests included in the project.  For instance, you've updated the `googleapis` package from `59.0.0` to `84.0.0`.  How is this package being used?  Are there any tests that will ensure that we know that updating a major version will cause an issue?  (Note: in this case you're fine, it isn't actively being used in the project - but in that case we should remove, rather than update it).

For each major package update, please research what the breaking changes are and document them (see ticket for instructions).  We want to make sure we as a team know what the downstream effects will be of performing a major version change.

## Pre
image
image

## Post
image
image

**Review by jasonwong26 — CHANGES_REQUESTED** [review]
See comment above.

**Comment by vadzimk** [comment]
@jasonwong26
 haveyou seen my comment in the issue discussion?

**Review by jasonwong26 — APPROVED** [review]
Hi @vadzimk,

I'm approving your changes.  There may be issues with the GitHub check actions (once those are in place) since you haven't updated the `yarn.lock` file, but we can address that in a subsequent ticket as needed.

**Comment by drubgrubby** [comment]
This PR is redundant and is being closed.

**Pull request closed without merging**
