### PR TITLE
Fix non unique email during new profile creation checkin

### PR DESCRIPTION
**Pull request by akibrhast**
- Add better error message returning from backend on non-unique email
- Added help utility post function that helps making post request by passing in endpoint and object
- Update front end code to account for the new error message type [WIP]

- Delete hack nights section from newUserForm component because we dont have hacknights anymore

- Delete alredy commented out code from returnUserForm component

- Fix fetch call for successfull checkIn for retuning user only by changing `returningUser._id` to `returningUser.user._id`
	in CheckInForm.js

- Deleted unused code from CheckInForm.js

- Removed unused props that were being passed to newUserForm and ReturnUserForm

- Consolidated repeated codes checking for url params

### CODE REVIEW

**Comment by drubgrubby** [comment]
@akibrhast -> This isn't passing the backend-integration  and  backend-unit test. I tried running the tests again but it still failed.

**Comment by akibrhast** [comment]
My bad. I should have noted down this is a work in progress and not ready for review.

**Comment by akibrhast** [comment]
Alllll testss passing !!!

**Comment by akibrhast** [comment]
I guess I could use a review on this 🗡️ 
Here is the link to the live version of this pull request.
- http://18.117.69.247/

**Pull request closed without merging**
