### PR TITLE
make new user email lowercase

### LINKED ISSUE #326: User email should be normalized to lowercase in database.
### Overview
During sign up, email address is stored as-is, If user types "FOO@BAR.COM", it is stored that way. Lookup is also case-sensitive, which it should not be.

### Action Items
Email should be stored as "foo@bar.com", lowercased in backend code. During lookup, any email address should be lowercased as well, in backend code.

### PR DESCRIPTION
**Pull request by vadzimk**
Closes #326

### CODE REVIEW

**Comment by drubgrubby** [comment]
@vadzimk -> This looks like it should work just fine.  However, when I went to test it it seems that the 'check in' button that should create the new user isn't working. It isn't working for me on the development branch either, so it's not your code.  

Is the check in button working for you? 

(I remember @jasonwong26 saying that it wasn't working for him a while ago, when it was still working for me.  So...?

**Comment by vadzimk** [comment]
@drubgrubby  I used the `client` instead of `client-mvp-04` to test it and it worked. The `client-mvp-04` will show 'not implemented'.

**Comment by drubgrubby** [comment]
@vadzimk -> Seems like the issue is on my end as it seems to be working for Jason and Alex at the moment.  Alex said he'd take a look at this PR while I try to figure out what the issue is on my end.

**Review by jasonwong26 — CHANGES_REQUESTED** [review]
Hi @vadzimk 

Overall, this looks really good!  One thing though - the email field is our primary key for the user model.  I think we're going to have issues we accept null values!  Please remove the optional chaining logic from your change.

```
const newUser = {
  ...req.body,
  //email: req.body.email?.toLowerCase()
  email: req.body.email.toLowerCase()
}
```

**Comment by vadzimk** [comment]
HI @jasonwong26 
Done

**Review by jasonwong26 — APPROVED** [review]
Looks good to me!  Approved.

**Pull request merged**
