### PR TITLE
Split backend

### LINKED ISSUE #553: Split 0.3 and 0.4 Backend/Frontend Code
We need to use separate branches for 0.3 and 0.4. 

This must happen before Docker fix.

### PR DESCRIPTION
**Pull request by alex-anakin**
Fixes #553 

This PR creates a separate backend application for MVP 0.4 by creating the `backend-mvp-04` directory and moving 0.4 specific files there.

### CODE REVIEW

**Comment by akibrhast** [comment]
@jasonwong26 , @drubgrubby , @jbubar , @mdPial , @glenflorendo , @mrao2 , @averdin2

Hey Folks,

> This PR creates a separate backend application for MVP 0.4 by creating the backend-mvp-04 directory and moving 0.4 specific files there.


Please review and test it out! If I did not mention someone please tag them in!

**Comment by piall** [comment]
Everything works fine for me :100:  . Maybe in different PR we can update our scripts command of `VRMS/package.json` .
```diff
- "mvp": "concurrently \"cd backend && npm run start\" \"cd client-mvp-04 && npm run start\"",
+ "mvp": "concurrently \"cd backend-mvp-04 && npm run start\" \"cd client-mvp-04 && npm run start\"",
```

**Review by akibrhast — COMMENTED** [review]
the controlller in v4 are empty
- was the scope of this pr to have v4 running
- or just take out v4 out of v3

is there a desire to have docker setup to have v03 and v04 simultaneously?

**Comment by mrao2** [comment]
@drubgrubby and I lookaed at the PR today. We confirm that 0.3 and 0.4 can run on their own. One change we had to make is that there was a "Role" model missing in the 0.3 backend that was causing an issue. Once we resolved it, it worked. 0.4 has no endpoints however the backend and frontend both run. I say we can merge.

**Comment by mrao2** [comment]
@alex-anakin It seems that you have moved the services folder from 0.3 backend to 0.4 backend does that mean that those services are not needed for 0.3?

**Review by mrao2 — APPROVED** [review]

**Pull request merged**
