### PR TITLE
Added 2021

### LINKED ISSUE #520: Adding the year 2021 for new user
### Overview
We need to add the year 2021 for new users in the check in page as right now it only shows 2020.

### Action Items
- [ ] Edit calendar on check in page to include 2021

### Resources/Instructions
Check In Page
image

### PR DESCRIPTION
**Pull request by akibrhast**
Added 2021
closes #520

### CODE REVIEW

**Comment by drubgrubby** [comment]
This looks good and appears to fix the issue.  Looks good to merge.

**Comment by switchzer0** [comment]
What logic options do we have to make the year choices "<= today's date[year]?" Would be nice not to hit the same snag in Jan 2022

**Comment by akibrhast** [comment]
> What logic options do we have to make the year choices "<= today's date[year]?" Would be nice not to hit the same snag in Jan 2022

 IMHO, given that this change was applied to the older client. It does not need a logical option to make the year choices. Especially since we are planning to move to the newer client at some point this year.

@switchzer0

**Comment by drubgrubby** [comment]
I agree with @akibrhast - and...

1) We should be sure to check that -- if this feature exists in future versions --  it automatically keeps dates current. 
2) It wouldn't be difficult to write a snippet that creates an array of this year and some number of years in the past.  But, as Akib suggested, rather then fix it, lets use it as some fire to put version .3 in the rear-view mirror.

**Review by drubgrubby — APPROVED** [review]

**Pull request merged**
