### PR TITLE
fix most warnings: usually useeffect and usecallback dependencies

### PR DESCRIPTION
**Pull request by evanyang1**
There were a good number of warnings (react related) when i run `npm run start`. I fixed most of them. Also, I cleaned up some of the code.

### CODE REVIEW

**Comment by glenflorendo** [comment]
Hey @evanyang1, nice work! Did you use a formatter / linter for your changes?

**Comment by evanyang1** [comment]
yes i did! I used Prettier (Facebook trained me to code in a certain way -- linting, clean code, etc..)

**Comment by glenflorendo** [comment]
> yes i did! I used Prettier (Facebook trained me to code in a certain way -- linting, clean code, etc..)

@evanyang1
Awesome! Could you please include your Prettier config file, so the team can see / review the rules that are being set?

**Comment by evanyang1** [comment]
I don't know how to access the json file for prettier. But I can let you know some of the settings:

2 spaces per tab
double quotes
always use parentheses for sole parameter in arrow functions

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@evanyang1 -> Nice work getting rid of the errors.  It's nice starting the app without all of those errors flying by.  Also, as Glen said, the code looks really nice.  

Sadly, one or some of your changes seem to have broken the app.  After running npm run start I logged into vrms and got the following error messages:

Screen Shot 2022-01-19 at 2 29 59 PM
Screen Shot 2022-01-19 at 2 30 08 PM
Screen Shot 2022-01-19 at 2 30 18 PM

Hopefully you can figure out which change broke the app.  If not, you may have to roll the changes back and do them one by one, checking each time to make sure it didn't break. 

Also, I noticed that there were still two errors that you didn't fix.  Any reason why?  If those errors were different and need some special attention, can you please create an issue for them? 
Screen Shot 2022-01-19 at 2 09 59 PM

**Comment by glenflorendo** [comment]
I'll take another look at this PR this week.

**Pull request closed without merging**
